apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-backup-config
  namespace: '{{ .Release.Namespace }}'
data:
  config.yaml: |
    paused: {{ .Values.backupPaused }}
    cadence: "{{ .Values.backupCadence }}"
