apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: '{{ .Values.etcdBackupJobMsiClientId }}'
    azure.workload.identity/tenant-id: '{{ .Values.tenantId }}'
  name: etcd-backup-job
  namespace: '{{ .Release.Namespace }}'