apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: '{{ .Values.hypershiftMsiClientId }}'
    azure.workload.identity/tenant-id: '{{ .Values.tenantId }}'
  name: hypershift
  namespace: '{{ .Release.Namespace }}'