{{- $clientIds := splitList "," $.Values.clientIds }}
{{- range $i, $_ := until (int $.Values.shardCount) }}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials-azure
  namespace: velero-{{ $i }}
type: Opaque
stringData:
  cloud: |-
    AZURE_SUBSCRIPTION_ID={{ $.Values.subscriptionId }}
    AZURE_TENANT_ID={{ $.Values.tenantId }}
    AZURE_CLIENT_ID={{ index $clientIds (mod $i (len $clientIds)) }}
    AZURE_RESOURCE_GROUP={{ $.Values.resourceGroup }}
    AZURE_CLOUD_NAME={{ $.Values.azureCloud }}
---
{{- end }}
