{{- range $i, $_ := until (int $.Values.shardCount) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-agent-{{ $i }}
  namespace: velero-{{ $i }}
spec:
  selector:
    matchLabels:
      name: node-agent
  namespaceSelector:
    matchNames:
    - velero-{{ $i }}
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
    scheme: http
    interval: 30s
---
{{- end }}
