{{- $clientIds := splitList "," $.Values.clientIds }}
{{- range $i, $_ := until (int $.Values.shardCount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: '{{ index $clientIds (mod $i (len $clientIds)) }}'
  name: velero
  namespace: velero-{{ $i }}
---
{{- end }}
